language: node_js
node_js:
  - "14"
dist: trusty
services:
  - mongodb
env:
  - MONGO_URI=mongodb://127.0.0.1:27017/db-test
cache:
  directories:
    - node_modules
before_install:
  - cd server
install:
  - npm install
script:
  - npm test
